- task: NuGetToolInstaller@1
  inputs:
    versionSpec:'5.0.0'
    
- task:NuGetCommand@2
  inputs:
    command:'restore'
    restoreSolution:'**/*.sln'
    feedsToUse:'select'
    vstsFeed:'a8bbf422-cfcb-472f-a927-5800276c0db3'